### ISSUE TITLE
Can I use it without composition-api in vue2 ? 

### ISSUE THREAD

**Issue by tu6ge** [logustra/vivu-npm#2]
why? I am maintaining a project with vue 2.6 , it have not composition-api , Can I use it ?

**Comment by logustra** [comment]
@tu6ge yap, as long as you write your library in vue 2 you don't need to install composition-api but if you write your library in vue 3 and want to use it in vue 2 as well, you need to install composition-api.

**Comment by tu6ge** [comment]
I try it failed,vite is not friendly with old version vue

**Comment by logustra** [comment]
@tu6ge any reproduce link that i can check?

**Comment by tu6ge** [comment]
After the project is packaged, I add it in project dependencies. In a third-party project, it tries to find some apis in vue3, but it cannot find them. So I give up and consider using other solutions
